# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adam Kostrzewa - Blog about Security and Embedded Design
email: adamkostrzewa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My technical blog presenting all aspects of security in embedded design.
  It presents the results of my private research.
  Feel free to participate in the discussion by leaving a comment or sending an email.
url: "https://adamkostrzewa.github.io/" # the base hostname & protocol for your site, e.g. http://example.com 
twitter_username: systemWbudowany
github_username:  AdamKostrzewa

# Build settings
markdown: kramdown
theme:  minima

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding comments false to that posts YAML Front Matter.
    shortname: https-adamkostrzewa-github-io

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
#exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
